#!/bin/sh

set -e

if dpkg --compare-versions "$2" lt-nl 2.3-24; then
	deb-systemd-helper purge anacron-resume.service >/dev/null
	deb-systemd-helper unmask anacron-resume.service >/dev/null
fi

# Automatically added by dh_installdeb/12.1.1
dpkg-maintscript-helper rm_conffile /etc/init/anacron.conf 2.3-26\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/apm/event.d/anacron 2.3-28\~ -- "$@"
# End automatically added section

