# LS
# Autogenerated from man page /usr/share/man/man6/LS.6.gz
complete -c LS -s a --description 'An accident seems to happen.  You\'ll feel pity for people who cry for help.'
complete -c LS -s l --description 'shows little one.'
complete -c LS -s F --description 'It flies.'
complete -c LS -s e --description 'Allow interrupt by Ctrl+C.'

