# mkfs
# Autogenerated from man page /usr/share/man/man8/mkfs.minix.8.gz
complete -c mkfs -l check --description 'Check the device for bad blocks before creating the filesystem.'
complete -c mkfs -l namelength --description 'Specify the maximum length of filenames.'
complete -c mkfs -l badblocks --description 'Read the list of bad blocks from R filename .'
complete -c mkfs -s 1 --description 'Make a Minix version 1 filesystem.   This is the default.'
complete -c mkfs -s 2 --description 'Make a Minix version 2 filesystem.'
complete -c mkfs -s 3 --description 'Make a Minix version 3 filesystem.'

