# querybts
# Autogenerated from man page /usr/share/man/man1/querybts.1.gz
complete -c querybts -s h -l help --description 'Show summary of options.'
complete -c querybts -l version --description 'Show the version of querybts and exit.'
complete -c querybts -s A -l archive --description 'Browse archived bugs instead of current reports.'
complete -c querybts -s B -l bts --description 'Instead of the Debian bug server, use the server specified by SYSTEM.'
complete -c querybts -s b -l buglist --description 'Display a bugs list for the given package.'
complete -c querybts -l latest-first --description 'Display the bug reports list sorted and with the latest reports at the top.'
complete -c querybts -l mbox-reader-cmd --description 'Specify a command to open the bug reports mbox file.'
complete -c querybts -s m -l mbox --description 'Retrieve the given bug number(s) or package name(s) as a mailbox file, instea…'
complete -c querybts -l proxy -l http_proxy --description 'Specify the WWW proxy server to use to handle the queries to the bug tracking…'
complete -c querybts -s s -l source --description 'Query on source packages, rather than binary packages.'
complete -c querybts -l timeout --description 'Specify the network timeout, the number of seconds to wait for a resource to …'
complete -c querybts -s u -l ui -l interface --description 'Specify the user interface to use.'
complete -c querybts -s w -l web --description 'Launch a web browser to view bug reports, instead of using the internal inter…'

