# sl
# Autogenerated from man page /usr/share/man/man6/sl.6.gz
complete -c sl -s a --description 'An accident seems to happen.  You\'ll feel pity for people who cry for help.'
complete -c sl -s l --description 'shows little one.'
complete -c sl -s F --description 'It flies.'
complete -c sl -s e --description 'Allow interrupt by Ctrl+C.'

