# tasksel
# Autogenerated from man page /usr/share/man/man8/tasksel.8.gz
complete -c tasksel -s t -l test --description 'test mode; don\'t actually install or remove packages.'
complete -c tasksel -l new-install --description 'automatically select some tasks without even displaying them to the user; def…'
complete -c tasksel -l list-tasks --description 'list on stdout the tasks that would be displayed in the tasksel interface.'
complete -c tasksel -l task-packages --description 'lists on stdout the packages that are available and part of the given task .'
complete -c tasksel -l task-desc --description 'outputs the extended description of the given task.'

